import 'dart:convert';

import 'package:crypto/crypto.dart';

/// SHA-256 hex digest, used for chat and endpoint ids (same scheme as the Android app).
String sha256Hex(String input) => sha256.convert(utf8.encode(input)).toString();

class ApiEndpoint {
  ApiEndpoint({required this.label, required this.host, this.apiKey = ''});

  final String label;
  final String host;
  final String apiKey;

  String get id => sha256Hex(label);

  Map<String, String> toJson() => {'label': label, 'host': host};

  factory ApiEndpoint.fromJson(Map<String, dynamic> json, String apiKey) =>
      ApiEndpoint(
        label: json['label'] as String? ?? '',
        host: json['host'] as String? ?? '',
        apiKey: apiKey,
      );
}

class ChatInfo {
  ChatInfo({required this.name, required this.timestamp, this.pinned = false});

  final String name;
  final int timestamp;
  final bool pinned;

  String get id => sha256Hex(name);

  ChatInfo copyWith({String? name, int? timestamp, bool? pinned}) => ChatInfo(
    name: name ?? this.name,
    timestamp: timestamp ?? this.timestamp,
    pinned: pinned ?? this.pinned,
  );

  Map<String, dynamic> toJson() => {
    'name': name,
    'timestamp': timestamp,
    'pinned': pinned,
  };

  factory ChatInfo.fromJson(Map<String, dynamic> json) => ChatInfo(
    name: json['name'] as String? ?? '',
    timestamp: int.tryParse('${json['timestamp']}') ?? 0,
    pinned: '${json['pinned']}' == 'true',
  );
}

class ChatMessage {
  ChatMessage({
    required this.text,
    required this.isBot,
    this.reasoning = '',
    this.imagePath = '',
    this.toolLog = '',
    this.contextText = '',
  });

  String text;
  final bool isBot;
  String reasoning;

  /// Local file: a picture sent by the user (vision) or generated by the model.
  String imagePath;

  /// Human-readable record of the tools the assistant called for this answer.
  String toolLog;

  /// Text captured from the user's screen and sent along with this message.
  String contextText;

  Map<String, dynamic> toJson() => {
    'message': text,
    'isBot': isBot,
    if (reasoning.isNotEmpty) 'reasoning': reasoning,
    if (imagePath.isNotEmpty) 'image': imagePath,
    if (toolLog.isNotEmpty) 'toolLog': toolLog,
    if (contextText.isNotEmpty) 'context': contextText,
  };

  factory ChatMessage.fromJson(Map<String, dynamic> json) => ChatMessage(
    text: '${json['message'] ?? ''}',
    isBot: json['isBot'] == true,
    reasoning: '${json['reasoning'] ?? ''}',
    imagePath: '${json['image'] ?? ''}',
    toolLog: '${json['toolLog'] ?? ''}',
    contextText: '${json['context'] ?? ''}',
  );
}

/// Per-chat generation settings.
class ChatSettings {
  ChatSettings({
    this.endpointId = '',
    this.model = 'gpt-4o',
    this.systemMessage = '',
    this.temperature = 0.7,
    this.topP = 1.0,
    this.frequencyPenalty = 0.0,
    this.presencePenalty = 0.0,
    this.maxTokens = 0,
    this.seed = '',
    this.assistantName = 'Grace',
    this.logitBiasSetId = '',
    this.functionCalling = false,
  });

  String endpointId;
  String model;
  String systemMessage;
  double temperature;
  double topP;
  double frequencyPenalty;
  double presencePenalty;
  int maxTokens;
  String seed;
  String assistantName;
  String logitBiasSetId;
  bool functionCalling;

  Map<String, dynamic> toJson() => {
    'endpointId': endpointId,
    'model': model,
    'systemMessage': systemMessage,
    'temperature': temperature,
    'topP': topP,
    'frequencyPenalty': frequencyPenalty,
    'presencePenalty': presencePenalty,
    'maxTokens': maxTokens,
    'seed': seed,
    'assistantName': assistantName,
    'logitBiasSetId': logitBiasSetId,
    'functionCalling': functionCalling,
  };

  factory ChatSettings.fromJson(Map<String, dynamic> json) {
    final d = ChatSettings();
    return ChatSettings(
      endpointId: json['endpointId'] as String? ?? d.endpointId,
      model: json['model'] as String? ?? d.model,
      systemMessage: json['systemMessage'] as String? ?? d.systemMessage,
      temperature: (json['temperature'] as num?)?.toDouble() ?? d.temperature,
      topP: (json['topP'] as num?)?.toDouble() ?? d.topP,
      frequencyPenalty:
          (json['frequencyPenalty'] as num?)?.toDouble() ?? d.frequencyPenalty,
      presencePenalty:
          (json['presencePenalty'] as num?)?.toDouble() ?? d.presencePenalty,
      maxTokens: (json['maxTokens'] as num?)?.toInt() ?? d.maxTokens,
      seed: json['seed'] as String? ?? d.seed,
      assistantName: json['assistantName'] as String? ?? d.assistantName,
      logitBiasSetId: json['logitBiasSetId'] as String? ?? d.logitBiasSetId,
      functionCalling: json['functionCalling'] as bool? ?? d.functionCalling,
    );
  }
}

/// A preset from assets/ai_sets.json.
class AiSet {
  AiSet({
    required this.name,
    required this.desc,
    required this.owner,
    required this.apiEndpoint,
    required this.apiEndpointName,
    required this.model,
    required this.suggestedChatName,
    required this.apiKeyUrl,
    required this.assistantName,
  });

  final String name;
  final String desc;
  final String owner;
  final String apiEndpoint;
  final String apiEndpointName;
  final String model;
  final String suggestedChatName;
  final String apiKeyUrl;
  final String assistantName;

  factory AiSet.fromJson(Map<String, dynamic> j) => AiSet(
    name: '${j['name'] ?? ''}',
    desc: '${j['desc'] ?? ''}',
    owner: '${j['owner'] ?? ''}',
    apiEndpoint: '${j['apiEndpoint'] ?? ''}',
    apiEndpointName: '${j['apiEndpointName'] ?? ''}',
    model: '${j['model'] ?? ''}',
    suggestedChatName: '${j['suggestedChatName'] ?? ''}',
    apiKeyUrl: '${j['apiKeyUrl'] ?? ''}',
    assistantName: '${j['assistantName'] ?? j['name'] ?? ''}',
  );
}

/// A named set of token biases sent as `logit_bias`.
class LogitBiasSet {
  LogitBiasSet({required this.id, required this.name, Map<String, int>? biases})
    : biases = biases ?? {};

  final String id;
  String name;

  /// Token id -> bias in the range -100..100.
  final Map<String, int> biases;

  Map<String, dynamic> toJson() => {'id': id, 'name': name, 'biases': biases};

  factory LogitBiasSet.fromJson(Map<String, dynamic> json) => LogitBiasSet(
    id: '${json['id']}',
    name: '${json['name'] ?? ''}',
    biases: {
      for (final e in (json['biases'] as Map? ?? {}).entries)
        '${e.key}': (e.value as num).toInt(),
    },
  );
}

/// A saved prompt from the prompts library.
class SavedPrompt {
  SavedPrompt({required this.id, required this.title, required this.text});

  final String id;
  String title;
  String text;

  Map<String, dynamic> toJson() => {'id': id, 'title': title, 'text': text};

  factory SavedPrompt.fromJson(Map<String, dynamic> json) => SavedPrompt(
    id: '${json['id']}',
    title: '${json['title'] ?? ''}',
    text: '${json['text'] ?? ''}',
  );
}

/// A self-hosted OpenAI-compatible speech server.
///
/// Speech to text: POST {host}/audio/transcriptions (for example Qwen3-ASR or Whisper servers).
/// Text to speech: POST {host}/audio/speech and GET {host}/audio/voices (for example Kokoro-FastAPI).
class SpeechServerConfig {
  SpeechServerConfig({
    this.enabled = false,
    this.host = '',
    this.apiKey = '',
    this.model = '',
    this.voice = 'af_heart',
    this.language = '',
  });

  bool enabled;

  /// Base URL including the version segment, such as http://192.168.1.2:8000/v1/
  String host;
  String apiKey;
  String model;

  /// Text to speech only.
  String voice;

  /// Speech to text only: language hint such as "en". Empty lets the server detect it.
  String language;

  /// Whether the server should be used instead of the built-in engine.
  bool get active => enabled && host.trim().isNotEmpty;

  Map<String, dynamic> toJson() => {
    'enabled': enabled,
    'host': host,
    'model': model,
    'voice': voice,
    'language': language,
  };

  factory SpeechServerConfig.fromJson(
    Map<String, dynamic> json,
    String apiKey,
  ) => SpeechServerConfig(
    enabled: json['enabled'] == true,
    host: '${json['host'] ?? ''}',
    apiKey: apiKey,
    model: '${json['model'] ?? ''}',
    voice: '${json['voice'] ?? 'af_heart'}',
    language: '${json['language'] ?? ''}',
  );
}
